spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P12A308?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    #jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P12A308?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    # jdbc:mysql://localhost:3306/ssafy
    hikari:
#      username: ssafy
#      password: ssafy123~
      username: S10P12A308@stg-yswa-kr-practice-db-master.mariadb.database.azure.com
      password: ${MARIADB_PW}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      globally_quoted_identifiers: true
      hibernate:
        format_sql: true
        show_sql: true
  security:
    user:
      name: hello
      password: 12345

jwt:
  secret: 'jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4'